import { z } from 'zod'
import { EncryptedBlobSchema } from './crypto'

/**
 * USER#<id> / ROADMAP — current focus/theme/direction. Content is encrypted;
 * nothing else here. `version` (Session 16) tracks how many times this has
 * been revised — starts at 1 at onboarding, incremented each time a
 * `RoadmapProposalItem` below is accepted, with the prior content archived
 * under `Sk.roadmapVersion(oldVersion)` at the same moment.
 */
/**
 * Intelligence Spec §17 "Roadmap Formation and Lifecycle" — named states
 * replacing the previously-implicit "the Roadmap just exists" model.
 * `emerging` has no corresponding RoadmapItem at all (it's the pre-onboarding
 * state — Companion is still gathering evidence, nothing persisted yet) and
 * `proposed` has no corresponding RoadmapItem either (that's what a pending
 * `RoadmapProposalItem` already represents structurally) — both are included
 * here for completeness with the spec's own enum, even though no live
 * RoadmapItem is ever written with those two values today: onboarding writes
 * directly to `active` (a deliberate, user-confirmed simplification — see
 * docs/AGENT_LOG.md's Living System Behaviors entry), and a proposal's own
 * existence is what "proposed" means, not a RoadmapItem field.
 */
export const RoadmapLifecycleStateSchema = z.enum([
  'emerging',
  'proposed',
  'confirmed',
  'active',
  'evolving',
  'paused',
  'archived',
])
export type RoadmapLifecycleState = z.infer<typeof RoadmapLifecycleStateSchema>

export const RoadmapItemSchema = z.object({
  pk: z.string(),
  sk: z.string(), // Sk.roadmap() or Sk.roadmapVersion(n) for history
  content: EncryptedBlobSchema, // wraps { currentFocus, theme, direction, suggestedSpaces }
  version: z.number().int().positive(),
  lifecycleState: RoadmapLifecycleStateSchema,
  updatedAt: z.string().datetime(),
})
export type RoadmapItem = z.infer<typeof RoadmapItemSchema>

/**
 * USER#<id> / ROADMAP#PROPOSED — a pending Roadmap revision (Session 16).
 * Generated by `roadmap/revise` whenever new confirmed Twin-signal evidence
 * accumulates right after a signal is confirmed (the trigger point and the
 * propose-first-don't-silently-rewrite framing were both the user's own
 * direct choice — see docs/AGENT_LOG.md Session 16 — mirroring the same
 * spec §5 Trust rules Twin signals themselves already follow). At most one
 * proposal exists per user at a time: a fresh evaluation while one is
 * already pending is skipped rather than stacking or overwriting it (see
 * lib/roadmap-revision.ts).
 */
export const RoadmapProposalItemSchema = z.object({
  pk: z.string(),
  sk: z.string(), // Sk.roadmapProposal()
  content: EncryptedBlobSchema, // wraps { currentFocus, theme, direction, suggestedSpaces, rationale }
  createdAt: z.string().datetime(),
})
export type RoadmapProposalItem = z.infer<typeof RoadmapProposalItemSchema>

/**
 * USER#<id> / ALIGNMENT#SNAPSHOT#<isoDate> — one item per user per day
 * (Session 19), written by the same scheduled-batch pattern
 * `compose-daily-card.ts`/`compose-weekly-recap.ts` already use. Plaintext
 * (just a number, no personal content) — exists purely so "My Evolution"
 * can chart the real Alignment Score over time instead of only ever
 * showing today's live-computed value. Starts empty for every user; the
 * chart is short/sparse until enough days accumulate — that's honest,
 * not a bug.
 */
export const AlignmentScoreSnapshotItemSchema = z.object({
  pk: z.string(),
  sk: z.string(), // Sk.alignmentScoreSnapshot(isoDate)
  date: z.string().date(),
  score: z.number().min(0).max(100),
  createdAt: z.string().datetime(),
})
export type AlignmentScoreSnapshotItem = z.infer<typeof AlignmentScoreSnapshotItemSchema>

/**
 * Digital Twin signal model (spec §5 "Signal model" / "Trust rules").
 * domain/status/confidence/source stay plaintext — they're what the
 * confirm/reject UI and the pipeline's write-path logic need to operate
 * on without decrypting. Only the descriptive text of the signal itself
 * is personal content.
 */
export const TwinSignalDomainSchema = z.enum([
  'pattern',
  'trigger',
  'value',
  'current_focus',
  'direction',
  'commitment',
])
export type TwinSignalDomain = z.infer<typeof TwinSignalDomainSchema>

export const TwinSignalStatusSchema = z.enum(['candidate', 'confirmed', 'rejected'])
export type TwinSignalStatus = z.infer<typeof TwinSignalStatusSchema>

export const TwinSignalSourceSchema = z.enum([
  'mirror_room',
  'decision_room',
  'companion',
  'onboarding',
  'explicit_user_input',
])
export type TwinSignalSource = z.infer<typeof TwinSignalSourceSchema>

/**
 * Life Domains taxonomy (Session 19) — the 7 categories Growth Tracker/My
 * Evolution Map/Dashboard all show percentages for. Labels match the
 * visual design reference exactly (`docs/UI reference for platform.pdf`).
 */
export const LifeDomainCategorySchema = z.enum([
  'self_inner_world',
  'relationships',
  'career_purpose',
  'health_body',
  'money_abundance',
  'creativity_expression',
  'spirituality',
])
export type LifeDomainCategory = z.infer<typeof LifeDomainCategorySchema>

export const LIFE_DOMAIN_LABELS: Record<LifeDomainCategory, string> = {
  self_inner_world: 'Self & Inner World',
  relationships: 'Relationships',
  career_purpose: 'Career & Purpose',
  health_body: 'Health & Body',
  money_abundance: 'Money & Abundance',
  creativity_expression: 'Creativity & Expression',
  spirituality: 'Spirituality',
}

/** Archetype taxonomy (Session 19) — same reference, "Leading Archetypes". */
export const ArchetypeSchema = z.enum(['healer', 'seeker', 'visionary', 'protector'])
export type Archetype = z.infer<typeof ArchetypeSchema>

export const ARCHETYPE_LABELS: Record<Archetype, string> = {
  healer: 'Healer',
  seeker: 'Seeker',
  visionary: 'Visionary',
  protector: 'Protector',
}

export const TwinSignalItemSchema = z.object({
  pk: z.string(),
  sk: z.string(), // Sk.twinSignal(domain, signalId)
  signalId: z.string(),
  domain: TwinSignalDomainSchema,
  status: TwinSignalStatusSchema,
  confidence: z.number().min(0).max(1),
  source: TwinSignalSourceSchema,
  sourceSessionId: z.string().optional(),
  content: EncryptedBlobSchema, // wraps { description: string }
  // Set at confirm-time (Session 19) by a real `twin/classify_signal`
  // Bedrock call (twin/confirm.ts → lib/signal-classification.ts) — absent
  // for signals confirmed before this existed, or if classification failed
  // (never blocks the confirm action itself; see that lib's doc comment).
  // Life Domains/Leading Archetypes on the Dashboard only aggregate over
  // signals that actually have these set — no fabricated 0%-everywhere
  // taxonomy for someone with zero classified signals.
  lifeDomain: LifeDomainCategorySchema.optional(),
  archetype: ArchetypeSchema.optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
})
export type TwinSignalItem = z.infer<typeof TwinSignalItemSchema>
