import type {
  GuidanceCardTopic,
  GuidanceCardLifeDomain,
  GuidanceCardCore,
  GuidanceCardDepth,
  GuidanceCardMode,
  GuidanceCardState,
  GuidanceCardRoute,
} from '@dpnr/shared-types'

/**
 * Companion "Pull a Card" library seed data — full 300-question bank from
 * `docs/DPNR_Pull_A_Card_300_Question_Bank_v2.pdf`, replacing Session 42's
 * 8-card placeholder set. Question `text` is extracted verbatim from the
 * source PDF (copied, not retyped or reworded) — the PDF's own card numbers
 * 001-300 are used as `cardId`, zero-padded to 3 digits, NOT prefixed with
 * the topic name. `topic` is certain: it is the source's own 10x30 chapter
 * structure (p.3 — "10 Topics. 300 Questions... 01 SELF - 30 cards ... 10
 * LIFE - 30 cards"), one topic per chapter, no judgment call involved.
 *
 * The other six metadata axes (`lifeDomain`, `core`, `depth`, `mode`,
 * `state`, `suggestedRoute`) are this session's own first-pass
 * classification, read card-by-card against the source doc's p.2
 * "Recommended metadata per card" axis definitions — **flagged for product
 * review, not treated as final**, same status every other net-new
 * authored/classified content set in this project carries before user
 * sign-off (see e.g. library-topics-v2.seed.ts's own doc comment for the
 * same pattern). `lifeDomain` is omitted wherever a card genuinely doesn't
 * land on one of the source's 9 life domains — per the source's own
 * guidance, this is expected and correct for a meaningful share of SELF /
 * FEEL / COURAGE / LIFE cards, not a gap to fill in later. Every card below
 * points at the existing `companion/pull-a-card.webp` placeholder until
 * real per-card art exists (same as the set this replaces).
 */
export interface GuidanceCardSeed {
  cardId: string
  text: string
  topic: GuidanceCardTopic
  lifeDomain?: GuidanceCardLifeDomain
  core: GuidanceCardCore
  depth: GuidanceCardDepth
  mode: GuidanceCardMode
  state: GuidanceCardState
  suggestedRoute: GuidanceCardRoute
}

export const GUIDANCE_CARD_SEEDS: GuidanceCardSeed[] = [
  // ---- SELF (001-030) ----
  { cardId: '001', text: 'Who are you when no one needs anything from you?', topic: 'SELF', core: 'Identity', depth: 'Deep', mode: 'Ask', state: 'Expansion', suggestedRoute: 'mirror_room' },
  { cardId: '002', text: 'What part of yourself are you getting to know right now?', topic: 'SELF', core: 'Identity', depth: 'Reflect', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'stay_on_card' },
  { cardId: '003', text: 'Where in your life do you feel most like yourself?', topic: 'SELF', core: 'Identity', depth: 'Everyday', mode: 'Notice', state: 'Connection', suggestedRoute: 'stay_on_card' },
  { cardId: '004', text: 'What version of you are you ready to outgrow?', topic: 'SELF', core: 'Identity', depth: 'Deep', mode: 'Choose', state: 'Expansion', suggestedRoute: 'mirror_room' },
  { cardId: '005', text: 'What do you know about yourself today that you did not know a year ago?', topic: 'SELF', core: 'Identity', depth: 'Reflect', mode: 'Remember', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '006', text: 'What do you wish people understood about you without you having to explain it?', topic: 'SELF', core: 'Identity', depth: 'Reflect', mode: 'Ask', state: 'Connection', suggestedRoute: 'main_chat' },
  { cardId: '007', text: 'What do you admire about the way you move through life?', topic: 'SELF', core: 'Identity', depth: 'Light', mode: 'Notice', state: 'Expansion', suggestedRoute: 'stay_on_card' },
  { cardId: '008', text: 'Where are you still trying to prove yourself?', topic: 'SELF', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '009', text: 'What part of you feels misunderstood?', topic: 'SELF', core: 'Identity', depth: 'Reflect', mode: 'Notice', state: 'Connection', suggestedRoute: 'main_chat' },
  { cardId: '010', text: 'What do you hide when you want to be accepted?', topic: 'SELF', core: 'Behavior', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '011', text: 'When do you feel most alive?', topic: 'SELF', core: 'Emotion', depth: 'Light', mode: 'Remember', state: 'Expansion', suggestedRoute: 'stay_on_card' },
  { cardId: '012', text: 'What makes you feel deeply connected to yourself?', topic: 'SELF', core: 'Identity', depth: 'Reflect', mode: 'Notice', state: 'Connection', suggestedRoute: 'stay_on_card' },
  { cardId: '013', text: 'What part of your personality has protected you for years?', topic: 'SELF', core: 'Pattern', depth: 'Deep', mode: 'Notice', state: 'Clarity', suggestedRoute: 'mirror_room' },
  { cardId: '014', text: 'What would change if you stopped trying to be who others expect?', topic: 'SELF', core: 'Belief', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'mirror_room' },
  { cardId: '015', text: 'Where are you more powerful than you give yourself credit for?', topic: 'SELF', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '016', text: 'What are you learning to accept about yourself?', topic: 'SELF', core: 'Identity', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '017', text: 'What do you want to be known for?', topic: 'SELF', core: 'Value', depth: 'Reflect', mode: 'Ask', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '018', text: 'Which part of yourself deserves more space?', topic: 'SELF', core: 'Need', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '019', text: 'What feels true about you even when everything else changes?', topic: 'SELF', core: 'Identity', depth: 'Deep', mode: 'Notice', state: 'Grounding', suggestedRoute: 'stay_on_card' },
  { cardId: '020', text: 'If you described yourself without roles, achievements, or relationships, who would you be?', topic: 'SELF', core: 'Identity', depth: 'Deep', mode: 'Ask', state: 'Expansion', suggestedRoute: 'mirror_room' },
  { cardId: '021', text: 'What side of you shows up most strongly at home?', topic: 'SELF', lifeDomain: 'Family', core: 'Identity', depth: 'Everyday', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'stay_on_card' },
  { cardId: '022', text: 'What side of you shows up most strongly at work?', topic: 'SELF', lifeDomain: 'Work-Career', core: 'Identity', depth: 'Everyday', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'stay_on_card' },
  { cardId: '023', text: 'What do you do differently when you feel fully comfortable?', topic: 'SELF', core: 'Behavior', depth: 'Everyday', mode: 'Notice', state: 'Grounding', suggestedRoute: 'stay_on_card' },
  { cardId: '024', text: 'What has surprised you about yourself lately?', topic: 'SELF', core: 'Identity', depth: 'Light', mode: 'Remember', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '025', text: 'What compliment is hardest for you to believe?', topic: 'SELF', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '026', text: 'What do you quietly want more recognition for?', topic: 'SELF', core: 'Need', depth: 'Reflect', mode: 'Notice', state: 'Connection', suggestedRoute: 'journal' },
  { cardId: '027', text: 'Where do you feel you have become more honest with yourself?', topic: 'SELF', core: 'Identity', depth: 'Reflect', mode: 'Remember', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '028', text: 'What do you miss about an earlier version of you?', topic: 'SELF', core: 'Identity', depth: 'Reflect', mode: 'Remember', state: 'Connection', suggestedRoute: 'journal' },
  { cardId: '029', text: 'What quality in yourself would you like to rely on more often?', topic: 'SELF', core: 'Value', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '030', text: 'If today revealed one thing about who you are becoming, what would it be?', topic: 'SELF', core: 'Identity', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'stay_on_card' },

  // ---- FEEL (031-060) ----
  { cardId: '031', text: 'What emotion has been asking for your attention lately?', topic: 'FEEL', core: 'Emotion', depth: 'Reflect', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '032', text: 'What are you feeling beneath the emotion you show first?', topic: 'FEEL', core: 'Emotion', depth: 'Deep', mode: 'Notice', state: 'Clarity', suggestedRoute: 'main_chat' },
  { cardId: '033', text: 'Which feeling do you find hardest to stay with?', topic: 'FEEL', core: 'Emotion', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '034', text: 'What happens inside you when you feel disappointed?', topic: 'FEEL', core: 'Emotion', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '035', text: 'What emotion do you tend to think about instead of actually feel?', topic: 'FEEL', core: 'Emotion', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '036', text: 'What are you trying not to feel right now?', topic: 'FEEL', core: 'Emotion', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '037', text: "What does your sadness need from you?", topic: 'FEEL', core: 'Need', depth: 'Reflect', mode: 'Ask', state: 'Grounding', suggestedRoute: 'journal' },
  { cardId: '038', text: 'What does your anger want you to know?', topic: 'FEEL', core: 'Emotion', depth: 'Reflect', mode: 'Ask', state: 'Clarity', suggestedRoute: 'main_chat' },
  { cardId: '039', text: 'What happens in your body when you feel safe?', topic: 'FEEL', core: 'Emotion', depth: 'Everyday', mode: 'Notice', state: 'Grounding', suggestedRoute: 'stay_on_card' },
  { cardId: '040', text: 'Which emotion changes your behavior the fastest?', topic: 'FEEL', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '041', text: "What feeling have you been carrying that may not belong to today?", topic: 'FEEL', core: 'Emotion', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '042', text: 'When you feel overwhelmed, what part of you takes over?', topic: 'FEEL', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '043', text: 'What emotion are you better at making room for in others than in yourself?', topic: 'FEEL', core: 'Emotion', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '044', text: 'What helps you return to yourself after an emotional wave?', topic: 'FEEL', core: 'Behavior', depth: 'Everyday', mode: 'Notice', state: 'Grounding', suggestedRoute: 'journal' },
  { cardId: '045', text: 'What would happen if you let yourself feel this without fixing it?', topic: 'FEEL', core: 'Emotion', depth: 'Reflect', mode: 'Choose', state: 'Grounding', suggestedRoute: 'main_chat' },
  { cardId: '046', text: 'Which emotion do you judge most quickly?', topic: 'FEEL', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '047', text: 'What is your body communicating before your mind understands it?', topic: 'FEEL', core: 'Emotion', depth: 'Reflect', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '048', text: 'What feeling do you wish you could express more freely?', topic: 'FEEL', core: 'Emotion', depth: 'Reflect', mode: 'Ask', state: 'Connection', suggestedRoute: 'main_chat' },
  { cardId: '049', text: 'What emotion has surprised you recently?', topic: 'FEEL', core: 'Emotion', depth: 'Light', mode: 'Remember', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '050', text: 'What would it mean to trust what you feel without letting it control you?', topic: 'FEEL', core: 'Belief', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'main_chat' },
  { cardId: '051', text: 'What feeling shaped the tone of your day today?', topic: 'FEEL', core: 'Emotion', depth: 'Light', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'stay_on_card' },
  { cardId: '052', text: 'What happened today that stayed with you longer than expected?', topic: 'FEEL', core: 'Emotion', depth: 'Light', mode: 'Remember', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '053', text: 'What are you feeling right now that you have not said out loud?', topic: 'FEEL', core: 'Emotion', depth: 'Reflect', mode: 'Notice', state: 'Connection', suggestedRoute: 'main_chat' },
  { cardId: '054', text: 'What do you usually need after a hard conversation?', topic: 'FEEL', core: 'Need', depth: 'Everyday', mode: 'Notice', state: 'Grounding', suggestedRoute: 'journal' },
  { cardId: '055', text: 'When was the last time your mood changed quickly, and what triggered it?', topic: 'FEEL', core: 'Pattern', depth: 'Light', mode: 'Remember', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '056', text: "What emotion are you carrying from someone else's energy today?", topic: 'FEEL', core: 'Emotion', depth: 'Light', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'stay_on_card' },
  { cardId: '057', text: 'What do you wish you had done differently with a feeling this week?', topic: 'FEEL', core: 'Behavior', depth: 'Reflect', mode: 'Remember', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '058', text: 'What helps you feel emotionally lighter within ten minutes?', topic: 'FEEL', core: 'Behavior', depth: 'Light', mode: 'Choose', state: 'Grounding', suggestedRoute: 'stay_on_card' },
  { cardId: '059', text: 'What feeling would you like to make more room for tomorrow?', topic: 'FEEL', core: 'Emotion', depth: 'Light', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '060', text: 'If your current mood could ask you for one thing, what would it ask for?', topic: 'FEEL', core: 'Need', depth: 'Light', mode: 'Ask', state: 'Curiosity', suggestedRoute: 'stay_on_card' },

  // ---- PATTERNS (061-090) ----
  { cardId: '061', text: 'What pattern keeps appearing in different areas of your life?', topic: 'PATTERNS', core: 'Pattern', depth: 'Deep', mode: 'Notice', state: 'Clarity', suggestedRoute: 'mirror_room' },
  { cardId: '062', text: 'What happens just before you repeat a behavior you later regret?', topic: 'PATTERNS', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '063', text: 'Which story about yourself have you repeated for so long that it feels like fact?', topic: 'PATTERNS', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '064', text: 'What do you automatically assume when someone pulls away?', topic: 'PATTERNS', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '065', text: 'What do you tend to do when you feel out of control?', topic: 'PATTERNS', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '066', text: 'What behavior once protected you but now limits you?', topic: 'PATTERNS', core: 'Pattern', depth: 'Deep', mode: 'Notice', state: 'Clarity', suggestedRoute: 'mirror_room' },
  { cardId: '067', text: 'What kind of situation brings out an older version of you?', topic: 'PATTERNS', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'mirror_room' },
  { cardId: '068', text: 'Where do you notice yourself repeating the familiar instead of choosing the healthy?', topic: 'PATTERNS', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '069', text: 'What belief about yourself would you like to question?', topic: 'PATTERNS', core: 'Belief', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'main_chat' },
  { cardId: '070', text: 'What do you expect to happen when things start going well?', topic: 'PATTERNS', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '071', text: 'What pattern do you recognize but still struggle to interrupt?', topic: 'PATTERNS', core: 'Pattern', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '072', text: 'Where do you confuse familiarity with safety?', topic: 'PATTERNS', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'mirror_room' },
  { cardId: '073', text: "What are you doing today because 'this is just how I am'?", topic: 'PATTERNS', core: 'Belief', depth: 'Everyday', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '074', text: 'Which fear quietly influences more decisions than you realize?', topic: 'PATTERNS', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '075', text: "What do you tend to make other people's behavior mean about you?", topic: 'PATTERNS', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'mirror_room' },
  { cardId: '076', text: 'What pattern shows up when you feel rejected?', topic: 'PATTERNS', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '077', text: 'Where do you become smaller to avoid conflict?', topic: 'PATTERNS', core: 'Boundary', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '078', text: 'What do you repeatedly tolerate and then resent?', topic: 'PATTERNS', core: 'Boundary', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '079', text: 'Which old story no longer fits the life you are building?', topic: 'PATTERNS', core: 'Belief', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '080', text: 'What might become possible if you stopped protecting the pattern and started understanding it?', topic: 'PATTERNS', core: 'Pattern', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'mirror_room' },
  { cardId: '081', text: 'What do you keep postponing in the same way every week?', topic: 'PATTERNS', core: 'Behavior', depth: 'Everyday', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '082', text: 'What happens to your habits when you are tired?', topic: 'PATTERNS', core: 'Behavior', depth: 'Light', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'stay_on_card' },
  { cardId: '083', text: 'Which situation reliably makes you overthink?', topic: 'PATTERNS', core: 'Pattern', depth: 'Everyday', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '084', text: 'What do you do on autopilot when you feel lonely?', topic: 'PATTERNS', core: 'Behavior', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '085', text: 'What small trigger tends to create a much bigger reaction in you?', topic: 'PATTERNS', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '086', text: "Where do you say 'it is fine' when it actually is not?", topic: 'PATTERNS', core: 'Boundary', depth: 'Everyday', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '087', text: 'What do you repeatedly promise yourself you will change?', topic: 'PATTERNS', core: 'Behavior', depth: 'Everyday', mode: 'Remember', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '088', text: 'Which pattern tends to appear when you have too much on your plate?', topic: 'PATTERNS', core: 'Pattern', depth: 'Everyday', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '089', text: 'What do you notice yourself doing when you are seeking reassurance?', topic: 'PATTERNS', core: 'Behavior', depth: 'Reflect', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '090', text: 'What is one recurring loop you could interrupt earlier next time?', topic: 'PATTERNS', core: 'Pattern', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },

  // ---- NEEDS (091-120) ----
  { cardId: '091', text: 'What do you need more of right now?', topic: 'NEEDS', core: 'Need', depth: 'Everyday', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '092', text: 'What do you need less of?', topic: 'NEEDS', core: 'Need', depth: 'Everyday', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '093', text: 'Which need have you been expecting someone else to notice without saying it?', topic: 'NEEDS', core: 'Need', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '094', text: 'What value are you unwilling to compromise anymore?', topic: 'NEEDS', core: 'Value', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '095', text: 'Where are your actions currently out of alignment with your values?', topic: 'NEEDS', core: 'Value', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '096', text: 'What boundary would create more peace in your life?', topic: 'NEEDS', core: 'Boundary', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '097', text: 'Where are you saying yes while feeling no?', topic: 'NEEDS', core: 'Boundary', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '098', text: 'What do you need in order to feel emotionally safe?', topic: 'NEEDS', core: 'Need', depth: 'Reflect', mode: 'Ask', state: 'Grounding', suggestedRoute: 'journal' },
  { cardId: '099', text: 'What are you afraid might happen if you set a clear boundary?', topic: 'NEEDS', core: 'Boundary', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '100', text: 'Which value guides your best decisions?', topic: 'NEEDS', core: 'Value', depth: 'Everyday', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '101', text: "What need do you often dismiss as 'too much'?", topic: 'NEEDS', core: 'Need', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '102', text: 'Where have you confused love with self-abandonment?', topic: 'NEEDS', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '103', text: 'What deserves a stronger no from you?', topic: 'NEEDS', core: 'Boundary', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '104', text: 'What deserves a fuller yes?', topic: 'NEEDS', core: 'Boundary', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'decision_room' },
  { cardId: '105', text: 'Which personal standard are you ready to raise?', topic: 'NEEDS', core: 'Value', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '106', text: 'Where are you asking others to respect something you are not respecting yourself?', topic: 'NEEDS', core: 'Boundary', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '107', text: 'What would honoring your needs look like today?', topic: 'NEEDS', core: 'Need', depth: 'Everyday', mode: 'Choose', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '108', text: 'What boundary would protect your energy without closing your heart?', topic: 'NEEDS', core: 'Boundary', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '109', text: 'Which need has been underneath your frustration lately?', topic: 'NEEDS', core: 'Need', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '110', text: 'What is one non-negotiable you want your future life to be built around?', topic: 'NEEDS', core: 'Value', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '111', text: 'What do you need before you can give your best to others today?', topic: 'NEEDS', core: 'Need', depth: 'Everyday', mode: 'Notice', state: 'Clarity', suggestedRoute: 'stay_on_card' },
  { cardId: '112', text: 'What are you craving that is not actually about food, shopping, or distraction?', topic: 'NEEDS', core: 'Need', depth: 'Reflect', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '113', text: 'Where in your schedule is there too little room for you?', topic: 'NEEDS', core: 'Boundary', depth: 'Everyday', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '114', text: 'What request would make your week easier if you actually made it?', topic: 'NEEDS', core: 'Need', depth: 'Everyday', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '115', text: 'What are you giving out of obligation rather than genuine willingness?', topic: 'NEEDS', core: 'Boundary', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '116', text: 'What need becomes loudest when you are stressed?', topic: 'NEEDS', core: 'Need', depth: 'Everyday', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '117', text: 'What would make your home feel more supportive this week?', topic: 'NEEDS', lifeDomain: 'Family', core: 'Need', depth: 'Everyday', mode: 'Choose', state: 'Grounding', suggestedRoute: 'journal' },
  { cardId: '118', text: 'What value do you want your next decision to protect?', topic: 'NEEDS', core: 'Value', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '119', text: 'Where could you replace guilt with a clearer boundary?', topic: 'NEEDS', core: 'Boundary', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'mirror_room' },
  { cardId: '120', text: 'What is one thing you can give yourself today instead of waiting for someone else to provide it?', topic: 'NEEDS', core: 'Need', depth: 'Everyday', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },

  // ---- LOVE (121-150) ----
  { cardId: '121', text: 'Who allows you to feel most like yourself?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Identity', depth: 'Everyday', mode: 'Notice', state: 'Connection', suggestedRoute: 'journal' },
  { cardId: '122', text: 'What do you tend to become afraid of when you care deeply about someone?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '123', text: 'What do you need in order to trust another person?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Need', depth: 'Reflect', mode: 'Ask', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '124', text: 'What do you give too easily in relationships?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Boundary', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '125', text: 'What do you struggle to receive?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '126', text: 'What kind of behavior makes you emotionally close down?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '127', text: 'How do you know when a relationship feels safe rather than simply intense?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'mirror_room' },
  { cardId: '128', text: 'Where do you abandon your own needs to preserve connection?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Boundary', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '129', text: 'What does being chosen mean to you?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Value', depth: 'Reflect', mode: 'Ask', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '130', text: 'What kind of love are you no longer willing to accept?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Boundary', depth: 'Deep', mode: 'Choose', state: 'Clarity', suggestedRoute: 'mirror_room' },
  { cardId: '131', text: 'How do you behave when you fear losing someone?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '132', text: 'Which relationship has taught you the most about yourself?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Identity', depth: 'Reflect', mode: 'Remember', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '133', text: 'What do you wish you could say more honestly to someone you love?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Boundary', depth: 'Reflect', mode: 'Notice', state: 'Connection', suggestedRoute: 'main_chat' },
  { cardId: '134', text: 'What do you need to forgive yourself for in a past relationship?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Belief', depth: 'Deep', mode: 'Remember', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '135', text: 'Where are you expecting someone to give you something you have not given yourself?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Need', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'mirror_room' },
  { cardId: '136', text: 'What makes you feel truly seen?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Need', depth: 'Reflect', mode: 'Notice', state: 'Connection', suggestedRoute: 'journal' },
  { cardId: '137', text: 'What relationship dynamic are you ready to stop recreating?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Pattern', depth: 'Deep', mode: 'Choose', state: 'Expansion', suggestedRoute: 'mirror_room' },
  { cardId: '138', text: 'What does healthy closeness look like to you now?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Value', depth: 'Reflect', mode: 'Ask', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '139', text: 'What would love feel like if you did not have to earn it?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Expansion', suggestedRoute: 'main_chat' },
  { cardId: '140', text: 'Who are you becoming inside your closest relationships?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Identity', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '141', text: 'Whose message or silence affected you more than you expected today?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Emotion', depth: 'Light', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'stay_on_card' },
  { cardId: '142', text: 'What conversation are you avoiding with someone close to you?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Boundary', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'decision_room' },
  { cardId: '143', text: 'Who do you feel safest being messy or imperfect around?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Need', depth: 'Everyday', mode: 'Notice', state: 'Connection', suggestedRoute: 'journal' },
  { cardId: '144', text: 'Where in a relationship are you currently guessing instead of asking?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Behavior', depth: 'Everyday', mode: 'Notice', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '145', text: 'What do you need more of in your closest connection: space, reassurance, honesty, affection, or play?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Need', depth: 'Everyday', mode: 'Choose', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '146', text: 'Who have you been missing lately, and what do you miss about them?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Emotion', depth: 'Light', mode: 'Remember', state: 'Connection', suggestedRoute: 'journal' },
  { cardId: '147', text: 'What small act of care would matter to someone you love today?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Behavior', depth: 'Light', mode: 'Act', state: 'Connection', suggestedRoute: 'stay_on_card' },
  { cardId: '148', text: 'Where are you taking someone close to you for granted?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Behavior', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '149', text: 'What would help you feel more connected at home this week?', topic: 'LOVE', lifeDomain: 'Family', core: 'Need', depth: 'Everyday', mode: 'Choose', state: 'Connection', suggestedRoute: 'journal' },
  { cardId: '150', text: 'What relationship deserves your attention before it becomes a problem?', topic: 'LOVE', lifeDomain: 'Relationships', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'decision_room' },

  // ---- COURAGE (151-180) ----
  { cardId: '151', text: 'What are you afraid would happen if you fully trusted yourself?', topic: 'COURAGE', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '152', text: 'What fear is currently disguised as practicality?', topic: 'COURAGE', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '153', text: 'What are you holding onto because uncertainty feels harder than discomfort?', topic: 'COURAGE', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '154', text: 'What would you attempt if embarrassment were impossible?', topic: 'COURAGE', core: 'Goal', depth: 'Light', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '155', text: 'What part of your life is fear making smaller?', topic: 'COURAGE', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '156', text: 'What are you ready to stop carrying?', topic: 'COURAGE', core: 'Boundary', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '157', text: 'What would courage look like in one small action today?', topic: 'COURAGE', core: 'Behavior', depth: 'Everyday', mode: 'Act', state: 'Expansion', suggestedRoute: 'decision_room' },
  { cardId: '158', text: 'Which decision are you delaying because you want certainty first?', topic: 'COURAGE', core: 'Goal', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'decision_room' },
  { cardId: '159', text: 'What are you afraid to admit that you want?', topic: 'COURAGE', core: 'Need', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '160', text: 'What are you afraid to admit that you no longer want?', topic: 'COURAGE', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '161', text: 'What might you lose if you change?', topic: 'COURAGE', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '162', text: 'What might you gain if you do?', topic: 'COURAGE', core: 'Goal', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '163', text: 'Which fear deserves curiosity instead of obedience?', topic: 'COURAGE', core: 'Belief', depth: 'Reflect', mode: 'Choose', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '164', text: 'What have you survived that once felt impossible?', topic: 'COURAGE', core: 'Identity', depth: 'Reflect', mode: 'Remember', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '165', text: 'What would you release if you trusted that letting go creates space?', topic: 'COURAGE', core: 'Boundary', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '166', text: 'Where are you staying loyal to something that is no longer loyal to you?', topic: 'COURAGE', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '167', text: 'What uncomfortable truth might actually set you free?', topic: 'COURAGE', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '168', text: 'What are you ready to stop proving?', topic: 'COURAGE', core: 'Belief', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '169', text: 'If fear were not making the decision, what would you choose?', topic: 'COURAGE', core: 'Goal', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '170', text: 'What is one thing your future self would thank you for releasing now?', topic: 'COURAGE', core: 'Boundary', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '171', text: 'What small risk have you been talking yourself out of?', topic: 'COURAGE', core: 'Goal', depth: 'Everyday', mode: 'Notice', state: 'Challenge', suggestedRoute: 'decision_room' },
  { cardId: '172', text: 'What do you want to say but keep editing in your head?', topic: 'COURAGE', core: 'Boundary', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '173', text: 'What would you do today if you were willing to be a little uncomfortable?', topic: 'COURAGE', core: 'Behavior', depth: 'Everyday', mode: 'Act', state: 'Expansion', suggestedRoute: 'decision_room' },
  { cardId: '174', text: 'Where are you waiting for someone else to go first?', topic: 'COURAGE', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '175', text: 'What are you tolerating because change feels inconvenient?', topic: 'COURAGE', core: 'Boundary', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '176', text: 'What would it look like to choose yourself without making anyone else wrong?', topic: 'COURAGE', core: 'Belief', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '177', text: 'What is one brave conversation that could create relief?', topic: 'COURAGE', core: 'Boundary', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'decision_room' },
  { cardId: '178', text: 'What are you ready to stop checking for permission around?', topic: 'COURAGE', core: 'Boundary', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '179', text: 'Where would honesty require more courage than silence?', topic: 'COURAGE', core: 'Boundary', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '180', text: 'What can you release today that you do not need to solve forever?', topic: 'COURAGE', core: 'Boundary', depth: 'Everyday', mode: 'Choose', state: 'Grounding', suggestedRoute: 'journal' },

  // ---- BODY (181-210) ----
  { cardId: '181', text: 'Where in your body are you holding tension today?', topic: 'BODY', lifeDomain: 'Health', core: 'Emotion', depth: 'Everyday', mode: 'Notice', state: 'Grounding', suggestedRoute: 'stay_on_card' },
  { cardId: '182', text: 'What changes in your body when you feel emotionally safe?', topic: 'BODY', lifeDomain: 'Health', core: 'Emotion', depth: 'Reflect', mode: 'Notice', state: 'Grounding', suggestedRoute: 'stay_on_card' },
  { cardId: '183', text: 'What does your body do when your answer is truly no?', topic: 'BODY', lifeDomain: 'Health', core: 'Behavior', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '184', text: 'What does your body do when something feels deeply right?', topic: 'BODY', lifeDomain: 'Health', core: 'Behavior', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'stay_on_card' },
  { cardId: '185', text: 'Where do you feel stress before you consciously notice it?', topic: 'BODY', lifeDomain: 'Health', core: 'Pattern', depth: 'Everyday', mode: 'Notice', state: 'Grounding', suggestedRoute: 'journal' },
  { cardId: '186', text: 'What has your body been asking you to slow down around?', topic: 'BODY', lifeDomain: 'Health', core: 'Need', depth: 'Reflect', mode: 'Notice', state: 'Grounding', suggestedRoute: 'journal' },
  { cardId: '187', text: 'What kind of movement helps you return to yourself?', topic: 'BODY', lifeDomain: 'Health', core: 'Behavior', depth: 'Light', mode: 'Notice', state: 'Grounding', suggestedRoute: 'stay_on_card' },
  { cardId: '188', text: 'What drains your energy faster than you expect?', topic: 'BODY', lifeDomain: 'Health', core: 'Pattern', depth: 'Everyday', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '189', text: 'What restores you?', topic: 'BODY', lifeDomain: 'Health', core: 'Need', depth: 'Light', mode: 'Notice', state: 'Grounding', suggestedRoute: 'stay_on_card' },
  { cardId: '190', text: 'When was the last time you felt completely relaxed?', topic: 'BODY', lifeDomain: 'Health', core: 'Emotion', depth: 'Light', mode: 'Remember', state: 'Grounding', suggestedRoute: 'journal' },
  { cardId: '191', text: 'Where are you overriding your body in order to keep going?', topic: 'BODY', lifeDomain: 'Health', core: 'Behavior', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '192', text: 'What does exhaustion usually mean for you?', topic: 'BODY', lifeDomain: 'Health', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '193', text: 'What physical sensation appears when you feel emotionally triggered?', topic: 'BODY', lifeDomain: 'Health', core: 'Emotion', depth: 'Reflect', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '194', text: 'What does your body need from you today?', topic: 'BODY', lifeDomain: 'Health', core: 'Need', depth: 'Everyday', mode: 'Ask', state: 'Grounding', suggestedRoute: 'stay_on_card' },
  { cardId: '195', text: 'How do you recognize the difference between excitement and anxiety in your body?', topic: 'BODY', lifeDomain: 'Health', core: 'Emotion', depth: 'Reflect', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '196', text: 'When do you breathe most freely?', topic: 'BODY', lifeDomain: 'Health', core: 'Emotion', depth: 'Light', mode: 'Notice', state: 'Grounding', suggestedRoute: 'stay_on_card' },
  { cardId: '197', text: 'What situation makes your body contract?', topic: 'BODY', lifeDomain: 'Health', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '198', text: 'What environment allows your nervous system to soften?', topic: 'BODY', lifeDomain: 'Health', core: 'Need', depth: 'Everyday', mode: 'Notice', state: 'Grounding', suggestedRoute: 'stay_on_card' },
  { cardId: '199', text: 'What would caring for your body look like if it were not about appearance?', topic: 'BODY', lifeDomain: 'Health', core: 'Value', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '200', text: 'What is your body trying to tell you that your mind keeps negotiating with?', topic: 'BODY', lifeDomain: 'Health', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '201', text: 'How is your energy different this morning compared with yesterday?', topic: 'BODY', lifeDomain: 'Health', core: 'Emotion', depth: 'Light', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'stay_on_card' },
  { cardId: '202', text: 'What did you do today that made your body feel better?', topic: 'BODY', lifeDomain: 'Health', core: 'Behavior', depth: 'Light', mode: 'Remember', state: 'Clarity', suggestedRoute: 'stay_on_card' },
  { cardId: '203', text: 'What are you doing too much of because you are running on momentum?', topic: 'BODY', lifeDomain: 'Health', core: 'Behavior', depth: 'Everyday', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '204', text: 'When did you last notice yourself holding your breath?', topic: 'BODY', lifeDomain: 'Health', core: 'Behavior', depth: 'Light', mode: 'Remember', state: 'Grounding', suggestedRoute: 'stay_on_card' },
  { cardId: '205', text: 'What would a ten-minute reset look like for you right now?', topic: 'BODY', lifeDomain: 'Health', core: 'Behavior', depth: 'Light', mode: 'Act', state: 'Grounding', suggestedRoute: 'stay_on_card' },
  { cardId: '206', text: 'What kind of rest do you actually need: sleep, quiet, movement, company, or mental space?', topic: 'BODY', lifeDomain: 'Health', core: 'Need', depth: 'Everyday', mode: 'Choose', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '207', text: 'What part of your routine supports your body best?', topic: 'BODY', lifeDomain: 'Health', core: 'Behavior', depth: 'Light', mode: 'Notice', state: 'Clarity', suggestedRoute: 'stay_on_card' },
  { cardId: '208', text: 'What everyday habit is quietly draining you?', topic: 'BODY', lifeDomain: 'Health', core: 'Pattern', depth: 'Everyday', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '209', text: 'What physical signal tells you that enough is enough?', topic: 'BODY', lifeDomain: 'Health', core: 'Boundary', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '210', text: 'If your body could set one priority for tomorrow, what would it choose?', topic: 'BODY', lifeDomain: 'Health', core: 'Goal', depth: 'Light', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },

  // ---- NEXT (211-240) ----
  { cardId: '211', text: 'What are you moving toward right now?', topic: 'NEXT', core: 'Goal', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '212', text: 'What are you moving away from?', topic: 'NEXT', core: 'Goal', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '213', text: 'What decision would simplify your life?', topic: 'NEXT', core: 'Goal', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '214', text: 'What matters enough to deserve your focus this season?', topic: 'NEXT', core: 'Value', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '215', text: 'If you could change one thing in the next six months, what would matter most?', topic: 'NEXT', core: 'Goal', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'decision_room' },
  { cardId: '216', text: 'What goal is truly yours?', topic: 'NEXT', core: 'Goal', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '217', text: 'Which goal are you pursuing because it looks good from the outside?', topic: 'NEXT', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '218', text: 'What would success feel like, not just look like?', topic: 'NEXT', core: 'Value', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '219', text: "What are you postponing until you feel 'ready'?", topic: 'NEXT', core: 'Pattern', depth: 'Everyday', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '220', text: 'What does your future self do differently from you today?', topic: 'NEXT', core: 'Goal', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '221', text: 'What needs to become less important for something more important to grow?', topic: 'NEXT', core: 'Value', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '222', text: 'What choice would create more self-respect?', topic: 'NEXT', core: 'Value', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '223', text: 'What do you already know about a decision you keep reconsidering?', topic: 'NEXT', core: 'Goal', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '224', text: 'Where are you waiting for permission?', topic: 'NEXT', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '225', text: 'What do you want your life to contain more of?', topic: 'NEXT', core: 'Value', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '226', text: 'What would a meaningful next chapter look like?', topic: 'NEXT', core: 'Goal', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '227', text: 'If your priorities were visible through your calendar, what would they reveal?', topic: 'NEXT', core: 'Value', depth: 'Everyday', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '228', text: 'What direction feels exciting and scary at the same time?', topic: 'NEXT', core: 'Goal', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '229', text: 'What small action could create momentum today?', topic: 'NEXT', core: 'Behavior', depth: 'Everyday', mode: 'Act', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '230', text: 'What are you building that is worth becoming someone new for?', topic: 'NEXT', core: 'Goal', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '231', text: 'What is the one task that would make today feel complete?', topic: 'NEXT', core: 'Behavior', depth: 'Light', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '232', text: 'What feels urgent today but may not actually matter?', topic: 'NEXT', core: 'Belief', depth: 'Light', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '233', text: 'What have you been spending time on that is not moving anything forward?', topic: 'NEXT', core: 'Behavior', depth: 'Everyday', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '234', text: 'What can wait until tomorrow without real consequences?', topic: 'NEXT', core: 'Goal', depth: 'Light', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '235', text: 'What decision would free up the most mental space this week?', topic: 'NEXT', core: 'Goal', depth: 'Everyday', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '236', text: 'What are you saying you have no time for that actually matters to you?', topic: 'NEXT', core: 'Value', depth: 'Everyday', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '237', text: 'What is one thing you can finish instead of carrying into another day?', topic: 'NEXT', core: 'Behavior', depth: 'Light', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '238', text: 'What would make tomorrow morning easier if you handled it today?', topic: 'NEXT', core: 'Behavior', depth: 'Light', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '239', text: 'What is the next useful step, not the perfect plan?', topic: 'NEXT', core: 'Goal', depth: 'Everyday', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '240', text: 'What would you choose today if your goal were progress rather than pressure?', topic: 'NEXT', core: 'Goal', depth: 'Everyday', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },

  // ---- CREATE (241-270) ----
  { cardId: '241', text: 'What does your work allow you to express about who you are?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Identity', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '242', text: 'What part of your professional life currently feels most alive?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Emotion', depth: 'Light', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '243', text: 'Where are you measuring your worth through productivity?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '244', text: 'What does enough mean to you financially?', topic: 'CREATE', lifeDomain: 'Finance', core: 'Value', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '245', text: 'What does money represent emotionally for you?', topic: 'CREATE', lifeDomain: 'Finance', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'main_chat' },
  { cardId: '246', text: 'What are you afraid success might cost you?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '247', text: 'What are you afraid failure would say about you?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Challenge', suggestedRoute: 'main_chat' },
  { cardId: '248', text: 'What kind of work would still matter to you without recognition?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Value', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '249', text: 'Where are you underestimating your value?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '250', text: 'What professional boundary would improve your life?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Boundary', depth: 'Reflect', mode: 'Choose', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '251', text: 'What are you creating that feels deeply yours?', topic: 'CREATE', core: 'Identity', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '252', text: 'When do you feel most creative?', topic: 'CREATE', core: 'Emotion', depth: 'Light', mode: 'Notice', state: 'Expansion', suggestedRoute: 'stay_on_card' },
  { cardId: '253', text: 'What shuts your creativity down?', topic: 'CREATE', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '254', text: 'What would you build if you knew it did not have to be perfect?', topic: 'CREATE', core: 'Goal', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '255', text: 'What are you trying to control in your professional life?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'mirror_room' },
  { cardId: '256', text: 'What does ambition give you?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Value', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '257', text: 'What does ambition take from you?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Value', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '258', text: 'What belief about money did you inherit rather than choose?', topic: 'CREATE', lifeDomain: 'Finance', core: 'Belief', depth: 'Deep', mode: 'Notice', state: 'Clarity', suggestedRoute: 'mirror_room' },
  { cardId: '259', text: 'What would healthy success look like for you?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Value', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '260', text: 'What do you want your work to contribute beyond achievement?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Value', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '261', text: 'What work task are you avoiding because it feels emotionally heavy?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Behavior', depth: 'Everyday', mode: 'Notice', state: 'Challenge', suggestedRoute: 'decision_room' },
  { cardId: '262', text: 'What would make your workday feel more human today?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Need', depth: 'Light', mode: 'Choose', state: 'Grounding', suggestedRoute: 'journal' },
  { cardId: '263', text: 'Where are you overcomplicating something that could be simple?', topic: 'CREATE', core: 'Behavior', depth: 'Everyday', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '264', text: 'What are you doing because it is important, and what are you doing because it looks productive?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '265', text: 'What idea keeps returning even though you have not acted on it?', topic: 'CREATE', core: 'Goal', depth: 'Reflect', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'decision_room' },
  { cardId: '266', text: 'What expense, purchase, or money decision has been sitting in the back of your mind?', topic: 'CREATE', lifeDomain: 'Finance', core: 'Goal', depth: 'Everyday', mode: 'Notice', state: 'Clarity', suggestedRoute: 'decision_room' },
  { cardId: '267', text: 'Where could you ask for help instead of carrying the whole thing yourself?', topic: 'CREATE', core: 'Boundary', depth: 'Everyday', mode: 'Notice', state: 'Challenge', suggestedRoute: 'decision_room' },
  { cardId: '268', text: 'What result are you chasing that may not be worth the cost?', topic: 'CREATE', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '269', text: 'What would you create if curiosity led before performance?', topic: 'CREATE', core: 'Value', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '270', text: 'What is one small professional win you have not properly acknowledged?', topic: 'CREATE', lifeDomain: 'Work-Career', core: 'Emotion', depth: 'Light', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },

  // ---- LIFE (271-300) ----
  { cardId: '271', text: 'What are you grateful for today that once felt ordinary?', topic: 'LIFE', core: 'Belief', depth: 'Light', mode: 'Notice', state: 'Connection', suggestedRoute: 'stay_on_card' },
  { cardId: '272', text: 'What moment recently reminded you that you are alive?', topic: 'LIFE', core: 'Emotion', depth: 'Light', mode: 'Remember', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '273', text: 'Where in your life is there already more abundance than you notice?', topic: 'LIFE', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '274', text: 'What simple thing brings you disproportionate joy?', topic: 'LIFE', core: 'Emotion', depth: 'Light', mode: 'Notice', state: 'Connection', suggestedRoute: 'stay_on_card' },
  { cardId: '275', text: 'When did life last surprise you in a good way?', topic: 'LIFE', core: 'Emotion', depth: 'Light', mode: 'Remember', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '276', text: 'What do you want to experience more deeply rather than achieve?', topic: 'LIFE', core: 'Value', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '277', text: 'What would make today feel meaningful?', topic: 'LIFE', core: 'Value', depth: 'Light', mode: 'Choose', state: 'Clarity', suggestedRoute: 'stay_on_card' },
  { cardId: '278', text: 'What deserves to be celebrated right now?', topic: 'LIFE', core: 'Emotion', depth: 'Light', mode: 'Notice', state: 'Connection', suggestedRoute: 'stay_on_card' },
  { cardId: '279', text: 'Who has made your life better simply by being in it?', topic: 'LIFE', lifeDomain: 'Relationships', core: 'Emotion', depth: 'Light', mode: 'Remember', state: 'Connection', suggestedRoute: 'journal' },
  { cardId: '280', text: 'What do you want to remember about this season of your life?', topic: 'LIFE', core: 'Value', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '281', text: 'When do you feel most connected to something larger than yourself?', topic: 'LIFE', lifeDomain: 'Spirituality', core: 'Emotion', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '282', text: 'What are you taking too seriously?', topic: 'LIFE', core: 'Belief', depth: 'Light', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'stay_on_card' },
  { cardId: '283', text: 'What would you do more often if joy were considered productive?', topic: 'LIFE', core: 'Value', depth: 'Light', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '284', text: 'What is beautiful in your life that you have stopped noticing?', topic: 'LIFE', core: 'Belief', depth: 'Light', mode: 'Notice', state: 'Connection', suggestedRoute: 'stay_on_card' },
  { cardId: '285', text: 'What experience would you love to give yourself this year?', topic: 'LIFE', lifeDomain: 'Leisure', core: 'Goal', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '286', text: 'Where could you choose curiosity instead of judgment?', topic: 'LIFE', core: 'Belief', depth: 'Everyday', mode: 'Choose', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '287', text: 'What part of your life is asking to be lived more fully?', topic: 'LIFE', core: 'Value', depth: 'Reflect', mode: 'Notice', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '288', text: 'What are you learning about what home means to you?', topic: 'LIFE', lifeDomain: 'Family', core: 'Value', depth: 'Reflect', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '289', text: 'If today were a message from your life, what might it be trying to show you?', topic: 'LIFE', core: 'Belief', depth: 'Reflect', mode: 'Notice', state: 'Curiosity', suggestedRoute: 'journal' },
  { cardId: '290', text: 'What would it mean to live this next chapter more consciously?', topic: 'LIFE', core: 'Value', depth: 'Reflect', mode: 'Choose', state: 'Expansion', suggestedRoute: 'journal' },
  { cardId: '291', text: 'What made you smile today, even briefly?', topic: 'LIFE', core: 'Emotion', depth: 'Light', mode: 'Remember', state: 'Connection', suggestedRoute: 'stay_on_card' },
  { cardId: '292', text: 'Who would you enjoy hearing from today?', topic: 'LIFE', lifeDomain: 'Relationships', core: 'Need', depth: 'Light', mode: 'Notice', state: 'Connection', suggestedRoute: 'stay_on_card' },
  { cardId: '293', text: 'What are you looking forward to this week?', topic: 'LIFE', core: 'Emotion', depth: 'Light', mode: 'Notice', state: 'Expansion', suggestedRoute: 'stay_on_card' },
  { cardId: '294', text: 'What part of your home or routine could use a little more care?', topic: 'LIFE', lifeDomain: 'Family', core: 'Behavior', depth: 'Everyday', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '295', text: 'What have you consumed today - news, social media, conversations - that changed your energy?', topic: 'LIFE', core: 'Behavior', depth: 'Everyday', mode: 'Notice', state: 'Clarity', suggestedRoute: 'journal' },
  { cardId: '296', text: 'What comparison stole some of your peace recently?', topic: 'LIFE', core: 'Pattern', depth: 'Reflect', mode: 'Notice', state: 'Challenge', suggestedRoute: 'journal' },
  { cardId: '297', text: 'What ordinary moment today deserves more appreciation?', topic: 'LIFE', core: 'Belief', depth: 'Light', mode: 'Notice', state: 'Connection', suggestedRoute: 'stay_on_card' },
  { cardId: '298', text: 'What would feel playful right now?', topic: 'LIFE', core: 'Emotion', depth: 'Light', mode: 'Choose', state: 'Expansion', suggestedRoute: 'stay_on_card' },
  { cardId: '299', text: 'What are you doing this week simply because you enjoy it?', topic: 'LIFE', lifeDomain: 'Leisure', core: 'Emotion', depth: 'Light', mode: 'Notice', state: 'Connection', suggestedRoute: 'stay_on_card' },
  { cardId: '300', text: 'What is one way you can make today feel more like your life, not just your to-do list?', topic: 'LIFE', core: 'Value', depth: 'Everyday', mode: 'Choose', state: 'Clarity', suggestedRoute: 'journal' },
]
