/**
 * One-off migration: the 7 legacy Twin Life Domain ids -> the Intelligence
 * Spec's 8 (§4). Proposal + mapping: docs/LIFE_DOMAINS_MIGRATION.md.
 *
 * Rewrites every plaintext copy of a legacy id:
 *   - `lifeDomain` on TWIN#SIGNAL, COMMITMENT#, OPENTHREAD# items
 *   - `activeDomains` on ONBOARDING_SNAPSHOT (deduplicated after mapping)
 *   - TWIN#DOMAIN_SUMMARY#<legacy id> items are derived and regenerated by
 *     `twin/domain_summary`, so they are deleted, not renamed
 *
 * Each write is conditional on the item still holding the legacy value, so a
 * re-run or a concurrent write never clobbers a newer value. Encrypted content
 * is never read or touched.
 *
 * Usage:
 *   cd infra/cdk
 *   npx ts-node --prefer-ts-exts scripts/migrate-life-domains-v8.ts            # dry run
 *   npx ts-node --prefer-ts-exts scripts/migrate-life-domains-v8.ts --confirm  # writes
 */
import { DynamoDBClient } from '@aws-sdk/client-dynamodb'
import { DeleteCommand, DynamoDBDocumentClient, ScanCommand, UpdateCommand } from '@aws-sdk/lib-dynamodb'

const TABLE_NAME = process.env.APPLICATION_TABLE_NAME ?? 'dpnr-application'
const SUMMARY_PREFIX = 'TWIN#DOMAIN_SUMMARY#'

/** Legacy id -> spec id. Ids not listed are unchanged. */
const LEGACY_TO_V8: Record<string, string> = {
  career_purpose: 'work_purpose',
  creativity_expression: 'work_purpose',
  spirituality: 'meaning_spirituality',
}

type Row = { pk: string; sk: string; lifeDomain?: string; activeDomains?: string[] }

async function scanCandidates(ddb: DynamoDBDocumentClient): Promise<Row[]> {
  const rows: Row[] = []
  let ExclusiveStartKey: Record<string, unknown> | undefined
  do {
    const page = await ddb.send(new ScanCommand({
      TableName: TABLE_NAME,
      ProjectionExpression: 'pk, sk, lifeDomain, activeDomains',
      FilterExpression: 'attribute_exists(lifeDomain) OR attribute_exists(activeDomains) OR begins_with(sk, :s)',
      ExpressionAttributeValues: { ':s': SUMMARY_PREFIX },
      ExclusiveStartKey,
    }))
    rows.push(...((page.Items ?? []) as Row[]))
    ExclusiveStartKey = page.LastEvaluatedKey
  } while (ExclusiveStartKey)
  return rows
}

async function main() {
  const confirm = process.argv.includes('--confirm')
  const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({}))
  const rows = await scanCandidates(ddb)

  let planned = 0
  let written = 0
  for (const row of rows) {
    const key = { pk: row.pk, sk: row.sk }

    if (row.sk.startsWith(SUMMARY_PREFIX)) {
      const domain = row.sk.slice(SUMMARY_PREFIX.length)
      if (!(domain in LEGACY_TO_V8)) continue
      planned++
      console.log(`DELETE ${row.pk} ${row.sk} (derived summary, regenerated under ${LEGACY_TO_V8[domain]})`)
      if (confirm) {
        await ddb.send(new DeleteCommand({ TableName: TABLE_NAME, Key: key }))
        written++
      }
      continue
    }

    if (row.lifeDomain && row.lifeDomain in LEGACY_TO_V8) {
      const next = LEGACY_TO_V8[row.lifeDomain]
      planned++
      console.log(`UPDATE ${row.pk} ${row.sk} lifeDomain ${row.lifeDomain} -> ${next}`)
      if (confirm) {
        await ddb.send(new UpdateCommand({
          TableName: TABLE_NAME,
          Key: key,
          UpdateExpression: 'SET lifeDomain = :next',
          ConditionExpression: 'lifeDomain = :prev',
          ExpressionAttributeValues: { ':next': next, ':prev': row.lifeDomain },
        }))
        written++
      }
    }

    if (row.activeDomains?.some((d) => d in LEGACY_TO_V8)) {
      const next = [...new Set(row.activeDomains.map((d) => LEGACY_TO_V8[d] ?? d))]
      planned++
      console.log(`UPDATE ${row.pk} ${row.sk} activeDomains [${row.activeDomains.join(', ')}] -> [${next.join(', ')}]`)
      if (confirm) {
        await ddb.send(new UpdateCommand({
          TableName: TABLE_NAME,
          Key: key,
          UpdateExpression: 'SET activeDomains = :next',
          ConditionExpression: 'activeDomains = :prev',
          ExpressionAttributeValues: { ':next': next, ':prev': row.activeDomains },
        }))
        written++
      }
    }
  }

  console.log(`\nScanned ${rows.length} domain-bearing items; ${planned} change(s) ${confirm ? `applied (${written})` : 'planned (dry run, nothing written; re-run with --confirm)'}.`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
