services:
  - type: web
    name: dpnr-web
    env: node
    branch: dpnr_course_site
    rootDir: dpnr-course-platform
    buildCommand: npm install && npm ls react react-dom && node -v && npm -v && npm run -w @dpnr/web build
    startCommand: npm run -w @dpnr/web start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      # Add your NEXT_PUBLIC_ variables here or via dashboard
      - key: NEXT_PUBLIC_URL
        value: https://dpnr-web.onrender.com
      - key: NEXT_PUBLIC_USER_POOL_ID
        value: il-central-1_tGk7FgEQk
      - key: NEXT_PUBLIC_CLIENT_ID
        value: 39vgapcn2tqlv3cn4fp9nlfgq1
